In [ ]:
 pip install yfinance

In [91]:
import yfinance as yf
import pandas as pd
import numpy as np

In [92]:
df=pd.read_csv('ind_nifty500list (4).csv')

In [93]:
df

               Sym
0       3MINDIA.NS
1           ABB.NS
2    POWERINDIA.NS
3           ACC.NS
4        AIAENG.NS
..             ...
496     YESBANK.NS
497        ZEEL.NS
498  ZENSARTECH.NS
499   ZYDUSWELL.NS
500      ECLERX.NS

[501 rows x 1 columns]

In [94]:
tickers=df.Sym.to_list()

In [96]:
mr=yf.download('^NSEI',start='2011-09-15',interval='1mo')

[*********************100%***********************]  1 of 1 completed

In [97]:
mr=mr['Adj Close']

In [98]:
mr=pd.DataFrame(mr)

In [99]:
mr

               Adj Close
Date
2011-09-01   4943.250000
2011-10-01   5326.600098
2011-11-01   4832.049805
2011-12-01   4624.299805
2012-01-01   5199.250000
...                  ...
2021-09-01  17618.150391
2021-10-01  17671.650391
2021-11-01  16983.199219
2021-12-01  16955.449219
2021-12-23  17072.599609

[125 rows x 1 columns]

In [103]:
mret=[0]
for i in range(1,len(mr)):
  mret.append((mr['Adj Close'][i]-mr['Adj Close'][i-1])*100/mr['Adj Close'][i])

In [ ]:
mret

In [105]:
mr['monthly returns']=mret

In [106]:
mr

               Adj Close  monthly returns
Date
2011-09-01   4943.250000         0.000000
2011-10-01   5326.600098         7.196900
2011-11-01   4832.049805       -10.234793
2011-12-01   4624.299805        -4.492572
2012-01-01   5199.250000        11.058329
...                  ...              ...
2021-09-01  17618.150391         2.758242
2021-10-01  17671.650391         0.302745
2021-11-01  16983.199219        -4.053719
2021-12-01  16955.449219        -0.163664
2021-12-23  17072.599609         0.686190

[125 rows x 2 columns]

In [ ]:
b=[]
for t in tickers:
  a=yf.download(t,start='2011-09-15',interval='1mo')
  b.append(a['Adj Close'])
c=pd.DataFrame(b)

In [109]:
c=pd.DataFrame(b)

In [110]:
c

Date       2011-09-01  2011-09-15  ...  2021-12-22    2021-12-23
Adj Close         NaN         NaN  ...         NaN  24812.250000
Adj Close         NaN         NaN  ...         NaN   2263.800049
Adj Close         NaN         NaN  ...         NaN   2555.500000
Adj Close  919.544922         NaN  ...         NaN   2150.800049
Adj Close         NaN         NaN  ...         NaN   1835.150024
...               ...         ...  ...         ...           ...
Adj Close         NaN         NaN  ...         NaN     13.550000
Adj Close  108.754837         NaN  ...         NaN    338.149994
Adj Close         NaN         NaN  ...         NaN    475.100006
Adj Close         NaN         NaN  ...         NaN   1889.300049
Adj Close  453.364838         NaN  ...         NaN   2291.449951

[501 rows x 1725 columns]

In [111]:
c.dropna(how='all',axis=1,inplace=True)
c.dropna(how='all',axis=0,inplace=True)

In [112]:
c

Date       2011-09-01   2011-10-01  ...    2021-12-01    2021-12-23
Adj Close         NaN  4270.100098  ...  25007.300781  24812.250000
Adj Close         NaN   667.681213  ...   2284.449951   2263.800049
Adj Close         NaN          NaN  ...   2527.699951   2555.500000
Adj Close  919.544922  1000.320496  ...   2149.899902   2150.800049
Adj Close         NaN   284.236877  ...   1815.599976   1835.150024
...               ...          ...  ...           ...           ...
Adj Close         NaN    56.827778  ...     13.650000     13.550000
Adj Close  108.754837   112.779373  ...    348.750000    338.149994
Adj Close         NaN    21.057323  ...    462.799988    475.100006
Adj Close         NaN   522.794800  ...   1872.599976   1889.300049
Adj Close  453.364838   464.208832  ...   2299.250000   2291.449951

[501 rows x 125 columns]

In [113]:
c.isna().sum().sum()

9387

In [114]:
c=c.reset_index()

In [115]:
c

Date      index  2011-09-01 00:00:00  ...  2021-12-01 00:00:00  2021-12-23 00:00:00
0     Adj Close                  NaN  ...         25007.300781         24812.250000
1     Adj Close                  NaN  ...          2284.449951          2263.800049
2     Adj Close                  NaN  ...          2527.699951          2555.500000
3     Adj Close           919.544922  ...          2149.899902          2150.800049
4     Adj Close                  NaN  ...          1815.599976          1835.150024
..          ...                  ...  ...                  ...                  ...
496   Adj Close                  NaN  ...            13.650000            13.550000
497   Adj Close           108.754837  ...           348.750000           338.149994
498   Adj Close                  NaN  ...           462.799988           475.100006
499   Adj Close                  NaN  ...          1872.599976          1889.300049
500   Adj Close           453.364838  ...          2299.250000          2291.449951

[501 rows x 126 columns]

In [116]:
c.drop('index',axis=1,inplace=True)

In [117]:
c

Date  2011-09-01   2011-10-01  ...    2021-12-01    2021-12-23
0            NaN  4270.100098  ...  25007.300781  24812.250000
1            NaN   667.681213  ...   2284.449951   2263.800049
2            NaN          NaN  ...   2527.699951   2555.500000
3     919.544922  1000.320496  ...   2149.899902   2150.800049
4            NaN   284.236877  ...   1815.599976   1835.150024
..           ...          ...  ...           ...           ...
496          NaN    56.827778  ...     13.650000     13.550000
497   108.754837   112.779373  ...    348.750000    338.149994
498          NaN    21.057323  ...    462.799988    475.100006
499          NaN   522.794800  ...   1872.599976   1889.300049
500   453.364838   464.208832  ...   2299.250000   2291.449951

[501 rows x 125 columns]

In [118]:
c.index=tickers

In [119]:
c

Date           2011-09-01   2011-10-01  ...    2021-12-01    2021-12-23
3MINDIA.NS            NaN  4270.100098  ...  25007.300781  24812.250000
ABB.NS                NaN   667.681213  ...   2284.449951   2263.800049
POWERINDIA.NS         NaN          NaN  ...   2527.699951   2555.500000
ACC.NS         919.544922  1000.320496  ...   2149.899902   2150.800049
AIAENG.NS             NaN   284.236877  ...   1815.599976   1835.150024
...                   ...          ...  ...           ...           ...
YESBANK.NS            NaN    56.827778  ...     13.650000     13.550000
ZEEL.NS        108.754837   112.779373  ...    348.750000    338.149994
ZENSARTECH.NS         NaN    21.057323  ...    462.799988    475.100006
ZYDUSWELL.NS          NaN   522.794800  ...   1872.599976   1889.300049
ECLERX.NS      453.364838   464.208832  ...   2299.250000   2291.449951

[501 rows x 125 columns]

In [120]:
c.iloc[:,1]

3MINDIA.NS       4270.100098
ABB.NS            667.681213
POWERINDIA.NS            NaN
ACC.NS           1000.320496
AIAENG.NS         284.236877
                    ...
YESBANK.NS         56.827778
ZEEL.NS           112.779373
ZENSARTECH.NS      21.057323
ZYDUSWELL.NS      522.794800
ECLERX.NS         464.208832
Name: 2011-10-01 00:00:00, Length: 501, dtype: float64

In [121]:
c=c[c.iloc[:,1]>0]

In [122]:
c

Date           2011-09-01   2011-10-01  ...    2021-12-01    2021-12-23
3MINDIA.NS            NaN  4270.100098  ...  25007.300781  24812.250000
ABB.NS                NaN   667.681213  ...   2284.449951   2263.800049
ACC.NS         919.544922  1000.320496  ...   2149.899902   2150.800049
AIAENG.NS             NaN   284.236877  ...   1815.599976   1835.150024
AARTIDRUGS.NS    3.765688     3.621408  ...    523.099976    521.099976
...                   ...          ...  ...           ...           ...
YESBANK.NS            NaN    56.827778  ...     13.650000     13.550000
ZEEL.NS        108.754837   112.779373  ...    348.750000    338.149994
ZENSARTECH.NS         NaN    21.057323  ...    462.799988    475.100006
ZYDUSWELL.NS          NaN   522.794800  ...   1872.599976   1889.300049
ECLERX.NS      453.364838   464.208832  ...   2299.250000   2291.449951

[368 rows x 125 columns]

In [123]:
c.isna().sum().sum()

242

In [ ]:
c.dropna(how='all',axis=0,inplace=True)
c.dropna(how='all',axis=0,inplace=True)

In [125]:
c

Date           2011-09-01   2011-10-01  ...    2021-12-01    2021-12-23
3MINDIA.NS            NaN  4270.100098  ...  25007.300781  24812.250000
ABB.NS                NaN   667.681213  ...   2284.449951   2263.800049
ACC.NS         919.544922  1000.320496  ...   2149.899902   2150.800049
AIAENG.NS             NaN   284.236877  ...   1815.599976   1835.150024
AARTIDRUGS.NS    3.765688     3.621408  ...    523.099976    521.099976
...                   ...          ...  ...           ...           ...
YESBANK.NS            NaN    56.827778  ...     13.650000     13.550000
ZEEL.NS        108.754837   112.779373  ...    348.750000    338.149994
ZENSARTECH.NS         NaN    21.057323  ...    462.799988    475.100006
ZYDUSWELL.NS          NaN   522.794800  ...   1872.599976   1889.300049
ECLERX.NS      453.364838   464.208832  ...   2299.250000   2291.449951

[368 rows x 125 columns]

In [126]:
c=c.iloc[:,1:]

In [127]:
for i in range(0,120):
  c=c[c.iloc[:,i]>0]

In [128]:
c

Date            2011-10-01   2011-11-01  ...    2021-12-01    2021-12-23
3MINDIA.NS     4270.100098  3814.600098  ...  25007.300781  24812.250000
ABB.NS          667.681213   561.126709  ...   2284.449951   2263.800049
ACC.NS         1000.320496   957.839966  ...   2149.899902   2150.800049
AIAENG.NS       284.236877   251.937286  ...   1815.599976   1835.150024
AARTIDRUGS.NS     3.621408     2.912636  ...    523.099976    521.099976
...                    ...          ...  ...           ...           ...
YESBANK.NS       56.827778    49.215786  ...     13.650000     13.550000
ZEEL.NS         112.779373   115.369873  ...    348.750000    338.149994
ZENSARTECH.NS    21.057323    20.015985  ...    462.799988    475.100006
ZYDUSWELL.NS    522.794800   407.462219  ...   1872.599976   1889.300049
ECLERX.NS       464.208832   451.562653  ...   2299.250000   2291.449951

[368 rows x 124 columns]

In [129]:
cl=[i for i in range(len(c.columns))]
c2=[i for i in range(len(c))]

In [130]:
c.columns=cl

In [131]:
c=pd.DataFrame(c)

In [132]:
c

                       0            1    ...           122           123
3MINDIA.NS     4270.100098  3814.600098  ...  25007.300781  24812.250000
ABB.NS          667.681213   561.126709  ...   2284.449951   2263.800049
ACC.NS         1000.320496   957.839966  ...   2149.899902   2150.800049
AIAENG.NS       284.236877   251.937286  ...   1815.599976   1835.150024
AARTIDRUGS.NS     3.621408     2.912636  ...    523.099976    521.099976
...                    ...          ...  ...           ...           ...
YESBANK.NS       56.827778    49.215786  ...     13.650000     13.550000
ZEEL.NS         112.779373   115.369873  ...    348.750000    338.149994
ZENSARTECH.NS    21.057323    20.015985  ...    462.799988    475.100006
ZYDUSWELL.NS    522.794800   407.462219  ...   1872.599976   1889.300049
ECLERX.NS       464.208832   451.562653  ...   2299.250000   2291.449951

[368 rows x 124 columns]

In [134]:
c.drop(labels=120,axis=1,inplace=True)
c.drop(labels=121,axis=1,inplace=True)

In [135]:
c=c[:119]

In [136]:
c

                       0            1    ...           122           123
3MINDIA.NS     4270.100098  3814.600098  ...  25007.300781  24812.250000
ABB.NS          667.681213   561.126709  ...   2284.449951   2263.800049
ACC.NS         1000.320496   957.839966  ...   2149.899902   2150.800049
AIAENG.NS       284.236877   251.937286  ...   1815.599976   1835.150024
AARTIDRUGS.NS     3.621408     2.912636  ...    523.099976    521.099976
...                    ...          ...  ...           ...           ...
FINCABLES.NS     32.860786    25.519075  ...    537.849976    534.599976
FINPIPE.NS       10.396699     7.906328  ...    207.050003    206.000000
FSL.NS            9.565020     6.850622  ...    160.149994    175.050003
FORTIS.NS       124.500000   113.599998  ...    277.799988    277.399994
GAIL.NS          90.944946    84.224632  ...    130.199997    132.850006

[119 rows x 122 columns]

In [137]:
c.isna().sum().sum()

1

In [138]:
sss=c.index

In [139]:
sss

Index(['3MINDIA.NS', 'ABB.NS', 'ACC.NS', 'AIAENG.NS', 'AARTIDRUGS.NS',
       'AARTIIND.NS', 'ABBOTINDIA.NS', 'ADANIENT.NS', 'ADANIPORTS.NS',
       'AEGISCHEM.NS',
       ...
       'ENGINERSIN.NS', 'ESCORTS.NS', 'EXIDEIND.NS', 'FDC.NS', 'FEDERALBNK.NS',
       'FINCABLES.NS', 'FINPIPE.NS', 'FSL.NS', 'FORTIS.NS', 'GAIL.NS'],
      dtype='object', length=119)

In [ ]:
import yfinance as yf

data = pd.DataFrame()
for t in sss:
    a=yf.download(t,start='2011-09-15',interval='1mo')
    data[t]=a['Adj Close']
    
sec_returns = np.log( data / data.shift(1))

In [142]:
sec_returns

            3MINDIA.NS    ABB.NS    ACC.NS  ...    FSL.NS  FORTIS.NS   GAIL.NS
Date                                        ...
2011-09-01         NaN       NaN       NaN  ...       NaN        NaN       NaN
2011-10-01    0.026988       NaN       NaN  ...       NaN        NaN       NaN
2011-11-01   -0.112801 -0.173864 -0.043395  ... -0.333773  -0.091622 -0.076767
2011-12-01   -0.073566 -0.022629 -0.006488  ... -0.264883  -0.299489 -0.020638
2012-01-01    0.015038  0.336080  0.048334  ...  0.319943   0.218382 -0.027348
...                ...       ...       ...  ...       ...        ...       ...
2021-09-01    0.017921 -0.013355 -0.068025  ...  0.075131  -0.097550  0.083327
2021-10-01    0.022623  0.125110  0.034398  ...  0.010937  -0.075656 -0.065021
2021-11-01   -0.014526 -0.027765 -0.020348  ... -0.153055   0.139246 -0.136944
2021-12-01   -0.001083  0.102522 -0.061557  ... -0.057332  -0.010741  0.003077
2021-12-23   -0.007830 -0.009080  0.000419  ...  0.088961  -0.001441  0.020149

[125 rows x 119 columns]

In [145]:
mret=[0]
for i in range(1,len(sec_returns)):
  mret.append((mr['Adj Close'][i]-mr['Adj Close'][i-1])*100/mr['Adj Close'][i])

In [146]:
mr['monthly returns']=mret

In [147]:
mr

               Adj Close  monthly returns
Date
2011-09-01   4943.250000         0.000000
2011-10-01   5326.600098         7.196900
2011-11-01   4832.049805       -10.234793
2011-12-01   4624.299805        -4.492572
2012-01-01   5199.250000        11.058329
...                  ...              ...
2021-09-01  17618.150391         2.758242
2021-10-01  17671.650391         0.302745
2021-11-01  16983.199219        -4.053719
2021-12-01  16955.449219        -0.163664
2021-12-23  17072.599609         0.686190

[125 rows x 2 columns]

In [148]:
infos=[]
for i in sss:
  infos.append(yf.Ticker(i).info)

In [149]:
infos=pd.DataFrame(infos)

In [150]:
infos.head()

       zip  ... toCurrency
0   560001  ...        NaN
1   560058  ...        NaN
2   400020  ...        NaN
3   380054  ...        NaN
4  400 022  ...        NaN

[5 rows x 157 columns]

In [151]:
beta=infos['beta']

In [152]:
beta.dropna(axis=0,how=all,inplace=True)

In [153]:
beta

0      0.423008
1      0.953539
2      0.648230
3      0.546902
4      1.083628
         ...
113    1.152519
114    1.043805
115    0.529646
116    0.832300
117    0.338495
Name: beta, Length: 117, dtype: float64

In [154]:
len(beta)

117

In [155]:
c

                       0            1    ...           122           123
3MINDIA.NS     4270.100098  3814.600098  ...  25007.300781  24812.250000
ABB.NS          667.681213   561.126709  ...   2284.449951   2263.800049
ACC.NS         1000.320496   957.839966  ...   2149.899902   2150.800049
AIAENG.NS       284.236877   251.937286  ...   1815.599976   1835.150024
AARTIDRUGS.NS     3.621408     2.912636  ...    523.099976    521.099976
...                    ...          ...  ...           ...           ...
FINCABLES.NS     32.860786    25.519075  ...    537.849976    534.599976
FINPIPE.NS       10.396699     7.906328  ...    207.050003    206.000000
FSL.NS            9.565020     6.850622  ...    160.149994    175.050003
FORTIS.NS       124.500000   113.599998  ...    277.799988    277.399994
GAIL.NS          90.944946    84.224632  ...    130.199997    132.850006

[119 rows x 122 columns]

In [156]:
t=10000000
s=10000000

In [ ]:
for i in range(0,len(c.columns)-3):
  sharpe=[]
  for j in range(0,len(c)):
    try:
      abc=beta[j]*(int(mret[i]) - 0.02) / (sec_returns[sss[j]].std() * 250 ** 0.5)
      sharpe.append([j,abc])
    except KeyError:
      sharpe.append([j,0])
  sh= sorted(sharpe, key=lambda x: x[1])
  abcd=sh[-20:]
  for k in range(0,20):
    d=c[i]
    e=c[i+1]
    s=s+((t/(d[abcd[k][0]]*20))*e[abcd[k][0]])-t/20
  t=s

In [158]:
print('ROI',s/10000000)

ROI 12.653704896825504